// frontend/src/features/photo-downloader/components/photo-gallery.tsx
import { For, Show } from "solid-js";

interface PhotosPreviewProps {
	photos: string[];
	loading: boolean;
}

export function PhotoGallery(props: PhotosPreviewProps) {
	return (
		<div class="grid gap-y-4 gap-x-2 grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 ">
			<Show
				when={!props.loading}
				fallback={
					<>
						<div class="rounded animate-pulse aspect-[3/4] bg-gray-500" />
						<div class="rounded animate-pulse aspect-[3/4] bg-gray-500" />
						<div class="rounded animate-pulse aspect-[3/4] bg-gray-500 hidden md:block" />
						<div class="rounded animate-pulse aspect-[3/4] bg-gray-500 hidden lg:block" />
						<div class="rounded animate-pulse aspect-[3/4] bg-gray-500 hidden xl:block" />
						<div class="rounded animate-pulse aspect-[3/4] bg-gray-500 hidden 2xl:block" />
					</>
				}
			>
				<For each={props.photos}>
					{(item) => (
						<div>
							<img
								src={item}
								alt=""
								class="min-h-48 object-top object-contain rounded"
								loading="lazy"
							/>
						</div>
					)}
				</For>
			</Show>
		</div>
	);
}

// frontend/src/lib/components/photo-gallery.svelte
<script lang="ts">
	import { photoStore } from "$lib/stores/photo-store.svelte";
	import type { ClassValue } from "svelte/elements";

	const { class: klass }: { class?: ClassValue } = $props();
</script>

<div
	class={[
		"grid grid-cols-2 gap-x-2 gap-y-4 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6",
		klass,
	]}
>
	{#if photoStore.loading}
		<div class="aspect-[3/4] animate-pulse rounded bg-gray-500"></div>
		<div class="aspect-[3/4] animate-pulse rounded bg-gray-500"></div>
		<div class="hidden aspect-[3/4] animate-pulse rounded bg-gray-500 md:block"></div>
		<div class="hidden aspect-[3/4] animate-pulse rounded bg-gray-500 lg:block"></div>
		<div class="hidden aspect-[3/4] animate-pulse rounded bg-gray-500 xl:block"></div>
		<div class="hidden aspect-[3/4] animate-pulse rounded bg-gray-500 2xl:block"></div>
	{:else}
		{#each photoStore.photos as photo}
			<div>
				<img src={photo} alt="" class="min-h-48 rounded object-contain object-top" loading="lazy" />
			</div>
		{/each}
	{/if}
</div>
